/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'category' : string,
  'isVegan' : boolean,
  'priceCents' : bigint,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'contact' : string,
  'totalAmountCents' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'quantity' : bigint, 'menuItemId' : bigint }
export interface _SERVICE {
  'addMenuItem' : ActorMethod<
    [string, string, bigint, string, boolean, boolean],
    MenuItem
  >,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getOrderById' : ActorMethod<[bigint], Order>,
  'placeOrder' : ActorMethod<[string, string, Array<OrderItem>, bigint], Order>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];